name: test-environment
channels:
  - conda-forge
dependencies:
  # Required
  - python=3.9
  - dask
  - distributed
  - pandas
  - pyarrow
  - snowflake-connector-python >=2.7.3
  - snowflake-sqlalchemy
  # Testing
  - pytest